<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 ../../../models/eye_blend/scene.gltf --transform
Author: Vinny Passmore (https://sketchfab.com/HPrendering)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eye-blend-a8259f43d41e4204a7e9746dfd112c30
Title: Eye Blend
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/models/eyeball-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Iris_Iris_001_Material_0.geometry}
			material={gltf.materials.Iris_001_Material}
			position={[0, 0, -2.82]}
			scale={123.88}
		/>
		<T.Mesh
			geometry={gltf.nodes.Sclera_Sclera_001_Material_0.geometry}
			material={gltf.materials.Sclera_001_Material}
			scale={120.46}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
