<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 ../../../../models/human_eye/scene.gltf --transform
Author: ScannerDev (https://sketchfab.com/maskutfab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-eye-7621abd3b4604d95bad90f9a1aaac51f
Title: Human Eye
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/models/eyeball.glb', { useDraco: true });
	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Sketchfab_Scene">
			<T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
				<T.Group name="root">
					<T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
						<T.Group name="Eye_2">
							<T.Group name="Cornea_0">
								<T.Mesh
									name="Object_6"
									geometry={gltf.nodes.Object_6.geometry}
									material={gltf.materials.Cornea}
								/>
							</T.Group>
							<T.Group name="Iris_1">
								<T.Mesh
									name="Object_8"
									geometry={gltf.nodes.Object_8.geometry}
									material={gltf.materials.Iris}
								/>
								<T.Mesh
									name="Object_9"
									geometry={gltf.nodes.Object_9.geometry}
									material={gltf.materials.Pupil}
								/>
							</T.Group>
							<T.Mesh
								name="Object_4"
								geometry={gltf.nodes.Object_4.geometry}
								material={gltf.materials.Eyeball}
							/>
						</T.Group>
					</T.Group>
				</T.Group>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
