<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 skeleton.gltf --transform
-->

<script>
	import { Group, MeshBasicMaterial } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/models/skeleton-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();

	const wireMaterial = new MeshBasicMaterial({
		color: 0x00ff00,
		wireframe: true
	});
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes['4639cb84395e47e89a734aa9882e7e37'].geometry}
			material={wireMaterial}
			rotation={[Math.PI / 2, 0, 0]}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
