<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 models/wrench/wrench.gltf --transform
-->

<script>
	import { Group, MeshBasicMaterial } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { colorScheme } from '$lib/stores';

	export const ref = new Group();

	const gltf = useGltf('/models/wrench-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();

	const wireMaterialDark = new MeshBasicMaterial({
		color: 0x6f6fff,
		wireframe: true
	});

	const wireMaterialLight = new MeshBasicMaterial({
		color: 0x0000f0,
		wireframe: true
	});

	let material = wireMaterialDark;

	$: {
		if ($colorScheme == 'dark') {
			material = wireMaterialDark;
		}
		if ($colorScheme == 'light') {
			material = wireMaterialLight;
		}
	}
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[0, 0.01, 0]} rotation={[-0.37, 0.18, -0.2]}>
			<T.Mesh
				geometry={gltf.nodes.defaultMaterial.geometry}
				{material}
				rotation={[Math.PI / 2, 0, 0]}
			/>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
